import React, { useState } from "react";
import FAQItem from "./FAQItem";

const FAQ_DATA = [
  {
    id: "1",
    question: "What is LM Protocol?",
    answer: "LM adds a leverage + margin trading layer on top of prediction markets so users can trade outcomes with x2–x10 leverage.",
  },
  {
    id: "2",
    question: "How does leverage work (and what is collateral)?",
    answer: "You deposit USDC as collateral, then select leverage to increase exposure; collateral absorbs losses and keeps the position open.",
  },
  {
    id: "3",
    question: "What is a liquidation price and what happens if I get liquidated?",
    answer: "Liquidation price is the level where your margin is too low; if reached, the protocol auto-closes your position to protect the vault.",
  },
  {
    id: "4",
    question: "Where does Vault APY come from?",
    answer: "From borrow interest paid by traders using leverage, plus trading fees generated by activity.",
  },
  {
    id: "5",
    question: "How does utilization affect borrowing rates and Vault APY?",
    answer: "Utilization = borrowed liquidity ÷ total vault liquidity. Higher utilization usually means higher borrow rates and higher LP yield.",
  },
  {
    id: "6",
    question: "What fees do traders pay?",
    answer: "Open/close fees on leveraged exposure, borrow interest while the trade is open, and a liquidation penalty if liquidated.",
  },
  {
    id: "7",
    question: "How does the USDC Vault generate yield for depositors?",
    answer: "Your USDC is lent to traders for leverage, and you earn yield from the interest they pay and protocol fees.",
  },
  {
    id: "8",
    question: "Who is the USDC Vault for?",
    answer: "For users who want passive, real yield linked to prediction market trading activity, not token inflation.",
  },
  {
    id: "9",
    question: "What makes LM different from a normal prediction market?",
    answer: "LM turns outcome shares into marginable positions with leverage, real-time liquidation levels, and pro-style trading tools.",
  },
  {
    id: "10",
    question: "How does LM keep the system safe for the Vault and traders?",
    answer: "Through maintenance margins, 24/7 risk monitoring, automated liquidations, and an insurance fund funded by a portion of fees.",
  },
];

export default function FAQAccordion() {
  const [openId, setOpenId] = useState(null);

  const handleToggle = (id) => {
    setOpenId((prev) => (prev === id ? null : id));
  };

  return (
    <div className="space-y-3" role="list">
      {FAQ_DATA.map((item) => (
        <FAQItem
          key={item.id}
          id={item.id}
          question={item.question}
          answer={item.answer}
          isOpen={openId === item.id}
          onToggle={handleToggle}
        />
      ))}
    </div>
  );
}
