import React from "react";
import { motion } from "framer-motion";
import { TrendingUp, Wallet } from "lucide-react";

const TRADER_STEPS = [
  "Connect your wallet",
  "Deposit USDC as collateral",
  "Choose a market and select leverage (x2–x10)",
  "Open a position and track your liquidation price",
  "Close anytime to realize profit or loss",
];

const LP_STEPS = [
  "Connect your wallet",
  "Deposit USDC into the Vault",
  "Earn yield generated by protocol activity (borrow interest + fees)",
  "Withdraw when liquidity is available",
];

export default function QuickStartCards() {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        className="p-6 rounded-xl bg-gray-900/60 border border-[#00FF99]/15 hover:border-[#00FF99]/25 hover:shadow-[0_0_30px_rgba(0,255,153,0.08)] transition-all"
      >
        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 rounded-lg bg-[#00FF99]/10 flex items-center justify-center">
            <TrendingUp className="w-5 h-5 text-[#00FF99]" />
          </div>
          <h3 className="text-lg font-bold text-white">For Traders</h3>
        </div>
        <ol className="space-y-3">
          {TRADER_STEPS.map((step, i) => (
            <li key={i} className="flex gap-3 text-gray-300 text-sm">
              <span className="flex-shrink-0 w-6 h-6 rounded-full bg-[#00FF99]/20 text-[#00FF99] text-xs font-bold flex items-center justify-center">
                {i + 1}
              </span>
              {step}
            </li>
          ))}
        </ol>
      </motion.div>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ delay: 0.1 }}
        className="p-6 rounded-xl bg-gray-900/60 border border-[#00FF99]/15 hover:border-[#00FF99]/25 hover:shadow-[0_0_30px_rgba(0,255,153,0.08)] transition-all"
      >
        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 rounded-lg bg-[#00FF99]/10 flex items-center justify-center">
            <Wallet className="w-5 h-5 text-[#00FF99]" />
          </div>
          <h3 className="text-lg font-bold text-white">For Liquidity Providers (USDC Vault)</h3>
        </div>
        <ol className="space-y-3">
          {LP_STEPS.map((step, i) => (
            <li key={i} className="flex gap-3 text-gray-300 text-sm">
              <span className="flex-shrink-0 w-6 h-6 rounded-full bg-[#00FF99]/20 text-[#00FF99] text-xs font-bold flex items-center justify-center">
                {i + 1}
              </span>
              {step}
            </li>
          ))}
        </ol>
      </motion.div>
    </div>
  );
}
